### ISSUE TITLE
Atividade prática: Gerenciador de Tarefas

### ISSUE THREAD

**Issue by ThiagoBussola** [TI-UNICESUMAR/2024-desafio-profissional-v-ESOFT5S-B#10]
Utilizando o template para uma API Rest fornecido em https://github.com/TI-UNICESUMAR/2024-desafio-profissional-v-ESOFT5S-B/tree/main/27-03-2024/books-api

Desenvolva um aplicativo para gerenciamento de tarefas.

check-list:
[] - Entender a atividade, isso envolve ver a atividade
[] - Instalar as dependências
[] - Opcional - Criar um dockerfile e um docker-compose.yml pra criar o container do banco escolhido
[] - Criar as entidades
[] - Da um check se o servidor está funcionando
[] - Criar a service para a entidade escolhida, e fazer o CRUD
[] - Fazer a controller
[] - Criar as rotas no arquivo de rotas
[] - Testar as rotas
[] - Partir para as rotas com regra de negócio

Entidades:

Usuário:
Atributos: ID, nome de usuário, peso, senha, e-mail.

Tasks:
Atributos: ID, título, descrição, data de criação, data de conclusão, tipo, categoria (opcional), status (pendente, em andamento, concluída), e usuário associado.

Categoria:
Atributos: ID, nome, cor (para identificação visual).

Tasks:

Rota para criação de uma nova tarefa.
Rota para listar todas as tarefas de um usuário.
Rota para obter detalhes de uma tarefa específica.
Rota para atualizar uma tarefa existente.
Rota para excluir uma tarefa.

Categorias:

Rota para criação de uma nova categoria.
Rota para listar todas as categorias de um usuário.
Rota para obter detalhes de uma categoria específica.
Rota para atualizar uma categoria existente.
Rota para excluir uma categoria.

Funcionalidades Adicionais utilizando Métodos de Array:

Rota para filtrar tarefas por categoria.
Rota para listar tarefas concluídas.
Rota para listar tarefas pendentes.
Rota para listar tarefas que vencem em um determinado período.
Rota para contar o número total de tarefas de um usuário.
Rota para encontrar a tarefa mais recente de um usuário.

Funcionalidades com Métodos de Array:

Rota para calcular a média de conclusão das tarefas.
Rota para encontrar a tarefa com a descrição mais longa.
Rota para agrupar tarefas por categoria.
Rota para encontrar a tarefa mais antiga de um usuário.
Observação:
Estas rotas podem ser implementadas utilizando os métodos .map, .filter, .resume, .some e outros métodos de manipulação de array para alcançar as funcionalidades desejadas, agregando complexidade média a difícil ao projeto.

**Comment by matheushb** [comment]
https://github.com/matheushb/express-todo-list

Informações sobre a API no README do projeto.

**Comment by rmcampigotto** [comment]
**https://github.com/rmcampigotto/esoft5sb-dpV/tree/main/AtividadeP01/backend**

RA: 220142052

**Comment by NathanLisandro** [comment]
https://github.com/NathanLisandro/CRUDtypescript
RA: 220199712

**Comment by Hudson-Matias** [comment]
https://github.com/Hudson-Matias/crud-typescript
RA: 22045746-2

**Comment by Matheus-Zauza-Maschietto** [comment]
https://github.com/Matheus-Zauza-Maschietto/Esoft5sb-desafio-profissional/tree/main/Atividade-gigante
RA: 22013969-2

**Comment by GabrielBitten** [comment]
https://github.com/GabrielBitten/Atividade-API

RA: 22257558-2

**Comment by GustavoZanardi15** [comment]
https://github.com/GustavoZanardi15/atividade-DesafioProfissional-

RA: 22225566-2

**Comment by Rafael-Days** [comment]
https://github.com/Rafael-Days/Atividade-20-03

RA: 22228632-2

**Comment by KauanMuriel** [comment]
https://github.com/KauanMuriel/task-manager-dpv

RA: 22014501-2

**Comment by AndreVassoler** [comment]
https://github.com/AndreVassoler/API-CRUD-FASTIFY-USER

RA: 22012716-2

**Comment by Matheus-Zauza-Maschietto** [comment]
https://github.com/Matheus-Zauza-Maschietto/Esoft5sb-desafio-profissional/tree/main/Atividade-gigante

RA: 22013969-2

**Comment by Muriloapv** [comment]
https://github.com/Muriloapv/DesafioProfV/tree/main/todo

**Comment by Muriloapv** [comment]
222151902
https://github.com/Muriloapv/DesafioProfV/tree/main/todo
