### ISSUE TITLE
Entrega Avaliação - Sagas do Universo Marvel

### ISSUE THREAD

**Issue by ThiagoBussola** [TI-UNICESUMAR/2024-desafio-profissional-v-ESOFT5S-B#14]
Faça a entrega nos comentários dessa issue, por favor indique os nomes e RAs presentes na dupla e o link para o repositório no github.
Faça somente uma entrega por dupla.

Data limite: 04/05/2024

**Comment by BielMaiolli** [comment]
RA: 221202002
RA: 221137422

Link: https://github.com/BielMaiolli/API-Marvel-TS

**Comment by GabrielBitten** [comment]
https://github.com/Rafael-Days/Marvel-Api-Bussola

Rafael Dias de Brito - 22228632-2
Gabriel Bittencourt Camillo de Souza - 22257558-2

**Comment by GabMalava** [comment]
https://github.com/GabMalava/MARVEL-API--ULTRON.git
Gabriel Malavazi RA:22145231-2

**Comment by Pedrogom7** [comment]
https://github.com/Pedrogom7/API-Marvel-DP5

Pedro Henrique Magalhães Gomes 
RA:22087525-2

Eduardo Voltatone Ribeiro das Neves
RA: 22207439-2

**Comment by alison-luiz** [comment]
https://github.com/alison-luiz/esoft_dp_v_avaliacao

Alison Luiz da Silva - RA: 22033281-2
Andre Fragalli Vassoler - RA: 22012716-2

**Comment by Lucasszsd** [comment]
https://github.com/Lucasszsd/api-marvel

Lucas Dutra Braga - ra : 22023711-2
Vlademir - ra : 22014195-2

**Comment by rmcampigotto** [comment]
Link: **https://github.com/rmcampigotto/MarvelAPI/tree/main/back**

RA: 22014205-2
RA: 23123581-2

Formulamos apresentação para o dia 08/04.

**Comment by matheushb** [comment]
https://github.com/matheushb/marvel-civil-war-api

Matheus Hoegen Baraldi 221589522
José Eduardo Centenaro Rocha 221100272

**Comment by IgorBondezam** [comment]
https://github.com/IgorBondezam/Marvel-API-1602

Igor Bondezam França -------- R.A.: 22012574-2
Mathus Zauza Maschietto ---- R.A.: 22013969-2
Bruno Batista Carrião Moreno R.A.: 24284115-2

**Comment by NathanLisandro** [comment]
Nathan Lisandro Toppa 22019971-2
Gabriel Presense 22143207-2

https://github.com/NathanLisandro/desafioProfissionalTrabalho

**Comment by diogo-cedran** [comment]
Link: https://github.com/diogo-cedran/API-Marvel

Diogo Tizolim Cedran RA: 22014212-2
Hudson Uccelli Matias dos Santos RA: 22045746-2

**Comment by Felipe-Tomazoti** [comment]
https://github.com/Felipe-Tomazoti/MarvelComics-API

Felipe Cesar Tomazoti de Souza, RA: 22019977-2
Vagner Rodrigues Calado Junior, RA: 22014296-2

**Comment by Vitorgooto** [comment]
https://github.com/Vitorgooto/API-Marvel

Vitor EIji Goto, RA:22145232-2
Gustavo Mesquita, RA:21099392-2

**Comment by LucianoGiraldi** [comment]
https://github.com/LucianoGiraldi/Marvel
RA: 22228890-2

**Comment by AlissonKobayashi** [comment]
https://github.com/GustavoZanardi15/ProvaPr-tica-Desafio-Profissional
Alisson Segura Kobayashi RA: 22210867-2
Gustavo Ulian Zanardi RA: 22225566-2

**Comment by JotaPeDark** [comment]
https://github.com/JotaPeDark/DesafioProfissional
João Pedro dos Santos Lussani R.A: 22014550-2
Wesley dos Santos David RA: 22171156-2

**Comment by PedroHLourenco** [comment]
https://github.com/mecoxeco/MarvelApp
Pedro Henrique de Abreu Lourenço RA: 22014566-2
Otávio Perez Luque RA: 22105800-2

**Comment by Muriloapv** [comment]
RA: 22215190-2
RA:222979642
https://github.com/igorosena/MarvelAPI

**Comment by roncon06** [comment]
RA:220143522 Lucas Roncon
RA:221379692 Vitoria Mendes
RA:220457482 Anna Julia
(OBS: Na planilha escolhemos a saga da Fenix Negra, porem acabamos utilizamos a saga da Guerra Civil)

https://github.com/roncon06/Marvel-Api.git

**Comment by Dudsnavarro** [comment]
https://github.com/Dudsnavarro/Desafio-APIMARVEL
RA 220145532
RA 220199732

**Comment by renanjava** [comment]
https://github.com/renanjava/api-marvel-bussola

RA: 22259135-2
RA: 22233538-2

**Comment by PabloVinif** [comment]
RA: 1993321-2
https://github.com/PabloVinif/APIMARVEL

**Comment by leofranchini** [comment]
https://github.com/leofranchini/api-marvel

Leonardo Demetrio Franchini: 22014274-2
Rodrigo Yaedu Pinesso: 22014201-2

**Comment by GH-eduardo** [comment]
Lucas Augusto Covaltchuk Calixto// RA: 22000109-2
Eduardo Thomé// RA: 22110037-2

https://github.com/GH-eduardo/API-Marvel

**Comment by B0nam** [comment]
https://github.com/KauanMuriel/marvel-nft

Daniel Bonam Rissardi: 22013838-2
Kauan Muriel Rossi: 2214501-2
