### ISSUE TITLE
Entrega Trabalho - To do List

### ISSUE THREAD

**Issue by ThiagoBussola** [TI-UNICESUMAR/2024-desafio-profissional-v-ESOFT5S-B#15]
Faça a entrega nos comentários dessa issue, por favor indique os nomes e RAs presentes na dupla e o link para o repositório no github.
Faça somente uma entrega por dupla.

Data Limite 29/04/2024

**Comment by AndreVassoler** [comment]
https://github.com/AndreVassoler/API-CRUD-FASTIFY-USER

RA: 22012716-2

**Comment by lucascovaltchuk** [comment]
https://github.com/lucascovaltchuk/CRUD_TASKS

RA: 22000109-2

**Comment by Felipe-Tomazoti** [comment]
https://github.com/Felipe-Tomazoti/Desafio_Profissional

RA: 22019977-2

**Comment by rmcampigotto** [comment]
https://github.com/rmcampigotto/esoft5sb-dpV/tree/main/AtividadeP01%20-%20Entrega/backend

RA: 22014205-2
RA: 23123581-2

**Comment by PabloVinif** [comment]
https://github.com/PabloVinif/TrabalhoDesafio

RA: 1993321-2

**Comment by BielMaiolli** [comment]
https://github.com/BielMaiolli/Crud-USER-TASK-CATEGORY

RA: 22120200-2
RA: 22113742-2

**Comment by joaorenzetti2** [comment]
https://github.com/joaorenzetti2/to-do-list/tree/main

RA: 22108621-2

**Comment by Lucasszsd** [comment]
https://github.com/Lucasszsd/task-api

RA : 22023711-2

**Comment by roncon06** [comment]
Lucas Roncon 22014352-2
Vitoria Mendes 221379692

https://github.com/roncon06/Task-Api.git

**Comment by alison-luiz** [comment]
https://github.com/alison-luiz/esoft_dp_v/tree/master/UsersTasks

R.A.: 22033281-2 (Alison Luiz da Silva)

**Comment by GabMalava** [comment]
https://github.com/GabMalava/Crud-Express/blob/main/crud-express/notes.txt
RA:22145231-2

**Comment by IgorBondezam** [comment]
https://github.com/IgorBondezam/esoft5b_dp/tree/master/atividade-20-03-2024-crud-fastify

R.A.:22012574-2     -   Igor Bondezam França

**Comment by PedroHLourenco** [comment]
https://github.com/mecoxeco/Typescript/tree/main/GerenciadorApp

RAs: 22014566-2 - Pedro Henrique de Abreu Lourenço/22105800-2 - Otávio Perez Luque

**Comment by matheushb** [comment]
https://github.com/matheushb/express-todo-list

221589522
matheus hoegen baraldi

**Comment by LucianoGiraldi** [comment]
https://github.com/LucianoGiraldi/Gerenciador-de-Tarefas-Desafio_Prof

RA: 22228890-2
RA: 21099392-2

**Comment by diogo-cedran** [comment]
https://github.com/diogo-cedran/desafio-profissional/tree/main/API%20Controle%20de%20Tarefas
RA: 22014212-2

**Comment by DevJPLussani** [comment]
https://github.com/DevJPLussani/DPesoft5s
R.A: 22014550-2
R.A:22171156-2

**Comment by GH-eduardo** [comment]
https://github.com/GH-eduardo/To-do-list

Eduardo Thomé
RA: 22110037-2

**Comment by Hudson-Matias** [comment]
https://github.com/Hudson-Matias/to-do-list
RA: 22045746-2

**Comment by Dudsnavarro** [comment]
https://github.com/Dudsnavarro/Trabalho-Desafio-Profissional-01

Eduardo Silvestre Navarro
RA 220145532

**Comment by rodrigopinesso** [comment]
https://github.com/rodrigopinesso/29-04

RA: 22014201-2
RA:22215190-2

**Comment by GabrielBitten** [comment]
https://github.com/GabrielBitten/Atividade-API

Gabriel Bittencourt Camillo de Souza - 22257558-2
Rafael Dias de Brito - 22228632-2

**Comment by renanjava** [comment]
https://github.com/renanjava/to-do-list-bussola
RA - 22259135-2
RA - 22233538-2

**Comment by NathanSenaa** [comment]
Nathan Sena - RA: 22019973-2
https://github.com/NathanSenaa/desafioprofissional
