### ISSUE TITLE
Trabalho 2 Bimestre - Definição de Times e API

### ISSUE THREAD

**Issue by ThiagoBussola** [TI-UNICESUMAR/2024-desafio-profissional-v-ESOFT5S-B#18]
Indique o nome e RA dos integrantes do grupo (Máximo 4 integrantes) e qual a API escolhida para desenvolver o trabalho

**Comment by MiguelGomesNogueira** [comment]
JOSÉ MIGUEL GOMES NOGUEIRA
22021680-2

IGOR BONDEZAM FRANÇA 
22012574-2

MATHEUS ZAUZA MASCHIETTO
22013969-2

Vagner Rodrigues Calado Junior  
22014296-2

API: https://developer.yahoo.com/api/

**Comment by alison-luiz** [comment]
ALISON LUIZ DA SILVA
22033281-2

FELIPE CESAR TOMAZOTI DE SOUZA
22019977-2

ANDRÉ FRAGALLI VASSOLER
22012716-2

API: https://api.cartola.globo.com

**Comment by B0nam** [comment]
DANIEL BONAM RISSARDI
22013838-2

BRUNO BATISTA CARRIÃO MORENO
24284115-2

KAUAN MURIEL ROSSI DA SILVA
22014501-2

API: https://developer.riotgames.com/apis

**Comment by LucianoGiraldi** [comment]
LUCIANO GIRALDI DE ANDRADE FILHO
22228890-2

VITOR EIJI GOTO
22145232-2

GUSTAVO HENRIQUE CORDEIRO MESQUITA
21099392-2

API: https://rickandmortyapi.com/

**Comment by Hudson-Matias** [comment]
Hudson Uccelli Matias dos Santos
RA: 22045746-2

Eduardo Voltatone 
RA: 22207439-2

Diogo Tizolim Cedran 
RA: 22014212-2

Pedro Henrique Magalhães Gomes 
RA: 22087525-2

API: https://pokeapi.co/

**Comment by matheushb** [comment]
Matheus Hoegen Baraldi
RA: 22158952-2

José Eduardo Centenaro Rocha
RA: 22110027-2

Gabriel Vinicius Maiolli
RA: 22120200-2

Vitor Bussioli Jorge 
RA: 22113742-2

API: https://developer.themoviedb.org

**Comment by Lucasszsd** [comment]
Lucas Dutra Braga 
22023711-2

Vlademir Vinhoto Junior
22014195-2

Lucas Leal Cardoso
22015777-2


https://deckofcardsapi.com

**Comment by renanjava** [comment]
Alisson Segura Kobayashi
22210867-2

Caio Henrique da Silva Verri 
22233538-2

Gustavo Ulian Zanardi 
22225566-2

Renan Geraldini Leão
22259135-2

API: https://valorant-api.com/

**Comment by PedroHLourenco** [comment]
Pedro Henrique de Abreu Lourenço
22014566-2

Otávio Perez Luque 
22105800-2

Eduardo Silvestre Navarro
22014553-2

Gabriel Presense
22143207-2

API: https://github.com/amafoas/one-piece-api

**Comment by rmcampigotto** [comment]
RAFAEL MANSO CAMPIGOTTO
RA: 22014205-2

JOAO HENRIQUE SALVALAGIO ABRAHIM
RA: 23123581-2

API: [https://rickandmortyapi.com/](https://rickandmortyapi.com/)
