### ISSUE TITLE
Atividade - 29/05/2024

### ISSUE THREAD

**Issue by ThiagoBussola** [TI-UNICESUMAR/2024-desafio-profissional-v-ESOFT5S-B#20]
1 - CRUD de produtos
- name
- value
- quantity

2 - Criar um middleware que pega o valor do produto e multiplica por 1.25

3 - Tratar as exception na controller e criar pelo menos uma exceção personalizada

4 - Adicionar o class-validator em todos os dtos

Data de entrega: dia 30/05/2024 23:59

**Comment by alison-luiz** [comment]
Alison Luiz da Silva
R.A.: 22033281-2

https://github.com/alison-luiz/esoft_dp_v/tree/master/Atividade2905

**Comment by matheushb** [comment]
Matheus Hoegen Baraldi
RA: 221589522

https://github.com/matheushb/nest-product-api

**Comment by IgorBondezam** [comment]
Igor Bondezam França
R.A 220125742

https://github.com/IgorBondezam/esoft5b_dp/tree/master/29-05-nest-atividade-middleware/Product-Middleware

**Comment by GustavoZanardi15** [comment]
Gustavo Ulian Zanardi 
RA: 22225566-2

https://github.com/GustavoZanardi15/atividade-DesafioProfissional-.git

**Comment by joaorenzetti2** [comment]
João Gabriel Renzetti
RA: 22108621-2

https://github.com/joaorenzetti2/desafio-profissional/tree/main/crud30-05

**Comment by Muriloapv** [comment]
Murilo Alves Pereira Varoto
RA:22215190-2

https://github.com/Muriloapv/DesafioProfV/tree/main/books-nest-29

**Comment by B0nam** [comment]
Daniel Bonam Rissardi
RA: 22013838-2

https://github.com/B0nam/ESOFT5S-B-NODE/tree/main/2024-05-29/product-api

**Comment by gustavochm1412** [comment]
Gustavo Henrique Cordeiro Mesquita 
RA: 21099392-2

https://github.com/gustavochm1412/desafioprof30

**Comment by GabrielBitten** [comment]
Gabriel Bittencourt Camillo de Souza
ra: 22257558-2

https://github.com/GabrielBitten/books-api

**Comment by Vitorgooto** [comment]
Vitor Eiji Goto
RA:221452322

https://github.com/Vitorgooto/DesafioProf5S

**Comment by ajprando** [comment]
Anna Julia Duarte Prando
RA: 220457482

https://github.com/ajprando/books-nest

**Comment by vitoriamendesz** [comment]
Vitoria Gabriele Mendonça Mendes 
RA:221379692

https://github.com/vitoriamendesz/books-nest

**Comment by lucascovaltchuk** [comment]
Lucas Augusto Covaltchuk Calixto
RA: 22000109-2

https://github.com/lucascovaltchuk/desafioprofissional

**Comment by roncon06** [comment]
Lucas Roncon
RA: 22014352-2

https://github.com/roncon06/books-nest.git

**Comment by AlissonKobayashi** [comment]
Alisson Segura Kobayashi
RA:22210867-2

https://github.com/AlissonKobayashi/Desafio_Profissional

**Comment by Pedrogom7** [comment]
Pedro Henrique Magalhães Gomes
RA: 22087525-2

https://github.com/Pedrogom7/DesafioProfissional/tree/main/Atividade%2029-05

**Comment by diogo-cedran** [comment]
Diogo Tizolim Cedran
RA: 22014212-2

https://github.com/diogo-cedran/desafio-profissional/tree/main/API%20Produtos%20-%20Nest

**Comment by eduvoltatone** [comment]
Eduardo Voltatone Ribeiro das Neves
RA: 22207439-2

https://github.com/eduvoltatone/DesafioProfissional

**Comment by AndreVassoler** [comment]
André Fragalli Vassoler
RA: 22012716-2

https://github.com/AndreVassoler/DP

**Comment by BielMaiolli** [comment]
Gabriel Vinicius Maiolli
RA: 221202002

https://github.com/BielMaiolli/atividadeDp

**Comment by renanjava** [comment]
Renan Geraldini Leão
RA: 22259135-2

https://github.com/renanjava/desafio-profissional-bussola/tree/main/atv_middleware_nest

**Comment by NathanSenaa** [comment]
Nathan Sena da Rocha 
RA: 22019973-2 


https://github.com/NathanSenaa/desafioprofissional/tree/main/atividade-29

**Comment by LuisZanin** [comment]
Luis Eduardo Zanin de Toledo
R.A.: 22199411-2

https://github.com/LuisZanin/Node-5S-A/tree/main/product-nest

**Comment by GH-eduardo** [comment]
Eduardo Thomé
RA: 221100372
https://github.com/GH-eduardo/DP

**Comment by leofranchini** [comment]
Leonardo Franchini
220142742
https://github.com/leofranchini/desafio-profissional-ativ

**Comment by Dudsnavarro** [comment]
Eduardo Silvestre Navarro
22145532
https://github.com/Dudsnavarro/DesafioProfissinal/tree/main/desafio-profissinal/atividade-DesafioProfissional--main

**Comment by Lucasszsd** [comment]
Lucas Dutra Braga 
22023711-2
https://github.com/Lucasszsd/trabalhonest

**Comment by GabrielMalava** [comment]
Gabriel Malavazi Rodrigues
RA:22145231-2
https://github.com/GabrielMalava/atividade29-05

**Comment by rodrigopinesso** [comment]
Rodrigo Yaedu Pinesso
RA: 22014201-2 

[https://github.com/rodrigopinesso/books-nest](url)
