### ISSUE TITLE
Entrega avaliação 2 Bimestre

### ISSUE THREAD

**Issue by ThiagoBussola** [TI-UNICESUMAR/2024-desafio-profissional-v-ESOFT5S-B#21]
Entregue o link do repositório da sua avaliação. Só é necessário uma entrega por grupo.

Na resposta junto ao link informe o nome e ra dos integrantes do time.
Nomes de integrante faltando não serão considerados então informe tudo corretamente. 

Deixe o repositório público ou envie o invite para seu repositório (caso envie o convite deixe informado na reposta que o convite foi enviado)

**Comment by matheushb** [comment]
Matheus Hoegen Baraldi
RA: 22158952-2

José Eduardo Centenaro Rocha
RA: 22110027-2

Gabriel Vinicius Maiolli
RA: 22120200-2

Vitor Bussioli Jorge
RA: 22113742-2

API: https://github.com/matheushb/movie-list-api

**Comment by alison-luiz** [comment]
Alison Luiz da Silva - RA: 22033281-2
Andre Fragalli Vassoler - RA: 22012716-2
Felipe Cesar Tomazoti de Souza - RA: 22019977-2

API: https://github.com/alison-luiz/esoft_prova_dp_v

**Comment by eduvoltatone** [comment]
Diogo Tizolim Cedran - RA: 22014212-2
Eduardo Voltatone - RA: 22207439-2
Hudson Uccelli Matias dos Santos - RA: 22045746-2
Pedro Henrique Magalhães Gomes - RA: 22087525-2

API: https://github.com/diogo-cedran/avaliacao_dp/tree/main

**Comment by Lucasszsd** [comment]
Lucas Dutra Braga
22023711-2

Vlademir Vinhoto Junior
22014195-2

Lucas Leal Cardoso
22015777-2

https://github.com/Lucasszsd/prova-2bim-nest

**Comment by roncon06** [comment]
Lucas Roncon Goncalves - RA: 22014352-2
Vitoria Mendes - RA: 22137969-2
Anna Julia - RA: 22045748-2

https://github.com/roncon06/api.git

**Comment by IgorBondezam** [comment]
Igor Bondezam França
R.A: 22012574-2

José Miguel Gomes Nogueira 
R.A: 22021680-2

Vagner Rodrigues Calado Junior
R.A: 22014296-2

Matheus Zauza Maschietto
R.A: 22013969-2

https://github.com/Matheus-Zauza-Maschietto/Financial-Markets

**Comment by mamisg142** [comment]
Flavio de Brito Silva 22240941-2
Nathan sena da Rocha 22019973-2
Gabriel Malavazi Rodrigues 22145231-2

API: https://github.com/mamisg/provadesafio2b

**Comment by B0nam** [comment]
Kauan Muriel Rossi da Silva
RA: 22014501-2

Daniel Bonam Rissardi
RA: 22013838-2

Bruno Batista Carrião Moreno
RA: 24284115-2

https://github.com/B0nam/league-live

**Comment by rmcampigotto** [comment]
RAFAEL MANSO CAMPIGOTTO
RA: 22014205-2

JOAO HENRIQUE SALVALAGIO ABRAHIM
RA: 23123581-2

Link Documentação: [Doc Postman]( https://documenter.getpostman.com/view/30407494/2sA3XWdyvf)
Link Repositório: [desafio-api](https://github.com/rmcampigotto/desafio-api)

Invite do git enviado.

**Comment by NathanLisandro** [comment]
Nathan Lisandro Toppa
RA: 220199712
https://github.com/NathanLisandro/POKEAPI

**Comment by mecoxeco** [comment]
Pedro Henrique de Abreu Lourenço
22014566-2

Otávio Perez Luque
22105800-2

Eduardo Silvestre Navarro
22014553-2

Gabriel Presense
22143207-2

API: https://github.com/mecoxeco/DesafioProfissionalV

**Comment by gustavochm1412** [comment]
Gustavo Henrique Cordeiro Mesquita 21099392-2
Vitor Eiji Goto 22145232-2
Luciano Giraldi de Andrade Filho 22228890-2

API : https://github.com/Vitorgooto/rick-and-morty-api

**Comment by AlissonKobayashi** [comment]
Alisson Segura Kobayashi RA: 22210867-2
Caio Henrique da Silva Verri RA: 22233538-2
Gustavo Ulian Zanardi RA: 22225566-2
Renan Geraldini Leão RA: 22259135-2

API: https://github.com/renanjava/desafio-profissional-bussola/tree/main/trabalho_jwt/trabalho-jwt

**Comment by zWesleyDavid** [comment]
Wesley dos Santos David
R.A: 22171156-2

João Pedro dos Santos Lussani
R.A: 22014550-2

Rafael Dias de Brito
R.A: 22228632-2

Gabriel Bittencourt Camillo de Souza
R.A: 22257558-2

API: https://github.com/zWesleyDavid/Prova-DP2B

**Comment by Muriloapv** [comment]
Murilo Varoto 222151902
Igor Sena 222979642
Rodrigo Pinesso 22014201-2

https://github.com/Muriloapv/desafioFinal
https://github.com/igorosena/crudFinal/tree/main

**Comment by lucascovaltchuk** [comment]
Lucas Augusto Covaltchuk Calixto
RA: 22000109-2

Eduardo Thomé
RA: 22110037-2

Leonardo Franchini
22014274-2

João Gabriel Renzetti
22018621-2

https://github.com/GH-eduardo/fintech
