### ISSUE TITLE
Entrega da atividade - 13-03-2024

### ISSUE THREAD

**Issue by ThiagoBussola** [TI-UNICESUMAR/2024-desafio-profissional-v-ESOFT5S-B#9]
Realize uma análise de melhorias e realizar o refactor do CRUD apresentado em aula afim de melhorar nossa aplicação

**Comment by GabrielBitten** [comment]
Atividade 13/03/2024 - Gabriel Bittencourt Camillo de Souza(RA-22257558-2)

Foi feito o CRUD completo no projeto, os seguintes métodos foram implementados:

-
- create: Cria um novo livro.
- findById: Busca um livro por ID.
- findAll: Busca todos os livros.
- update: Atualiza um livro por ID.
- deleteById: Deleta um livro por ID.
- deleteAll: Deleta todos os livros.

Como boa prática, em cada um dos métodos foi usado o tratamento de excessões(try catch) com retorno de 500 em caso de falhas, foi criado um arquivo .gitignore, onde a pasta node_modules é excluída do controle de versão do git, resultando em um repositório mais leve e limpo.

Sites utilizados:
https://stackoverflow.com/questions/52467266/nodejs-try-catch-and-res-status-usage
https://www.alura.com.br/artigos/async-await-no-javascript-o-que-e-e-quando-usar
https://mongoosejs.com/docs/api/model.html#Model.findByIdAndUpdate()
https://kb.objectrocket.com/mongo-db/mongoose-delete-many-724
https://www.atlassian.com/br/git/tutorials/saving-changes/gitignore

Repositório: https://github.com/GabrielBitten/Desafio-profissional

**Comment by rmcampigotto** [comment]
Primeiramente, adicionei o arquivo .gitignore e no mesmo coloquei a pasta node_modules, visto que ela seria muito pesada para importar para o repositório. Após isso, realizei a criação da função FindByID e FindAll, que retorna um registro pelo id dele e retorna full respectivamente, seguindo no CRUD, criei a função Update utilizando a função findByIdAndUpdate do Mongoose e a função Delete utilizando findByIdAndDelete também do Mongoose.

Utilizando export default new BookService() eu removi a necessidade de instanciar toda vez que iriamos chamar uma função do Service. Fazendo isso, utilizando um nome de variável na hora do import (exemplo: bookService) consegui utilizar sem ter de ficar instanciando a toda nova função que eu iria executar. Adicionei também try/catch em todas as requisições para tratamento de erros.

Links:
https://mongoosejs.com/docs/api/model.html#Model.findByIdAndUpdate()
https://mongoosejs.com/docs/api/model.html#Model.findByIdAndDelete()
https://expressjs.com/en/guide/routing.html
https://mongoosejs.com/docs/api/model.html#Model.findById()

Repositório:
https://github.com/rmcampigotto/esoft5sb-dpV/tree/main/aula02

RA: 22014205-2

**Comment by Rafael-Days** [comment]
-Adicionei os métodos getById, getAll, update e delete junto do método create em BookController. Em routes.ts adicionei os caminhos dos novos métodos.

-Em BookService, fiz com que as variáveis dos métodos pasassem um tipo, como o professor aconselhou em aula (não passar book: any em todos os métodos).

-Em BookService, usei findByIdAndUpdate() e findByIdAndDelete() em update e delete.

-Para não precisar instanciar um novo BookService() em todos os métodos, em BookController criei um construtor que instanciou BookService() e utilizei ele nos métodos.

-Dentro dos métodos assincronos de BookController, adicionei try cacth, para caso acontecesse um erro, retorná-lo.

Para essa atividade, utilizei os seguintes sites:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch

https://www.typescriptlang.org/pt/play#example/async-

https://mongoosejs.com/docs/api/model.html#Model.findByIdAndUpdate()

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

Repositório:
https://github.com/Rafael-Days/bookBussola
